const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const contenido={textContent:'',innerHTML:''};
let vendedor=true;
const contexto={esVendedor(){return vendedor},textoSeguro(x){return String(x)},document:{getElementById(){return contenido}}};
vm.createContext(contexto);
vm.runInContext(fs.readFileSync(path.join(__dirname,'..','js','manuales.js'),'utf8'),contexto);
contexto.iniciarManuales();
assert.match(contenido.innerHTML,/Nueva venta/);
assert.match(contenido.innerHTML,/Cuentas por cobrar/);
assert.doesNotMatch(contenido.innerHTML,/Conciliación/);
assert.doesNotMatch(contenido.innerHTML,/Usuarios/);
vendedor=false;
contexto.iniciarManuales();
assert.match(contenido.innerHTML,/Conciliación/);
assert.match(contenido.innerHTML,/Usuarios/);
console.log('Manuales por rol OK');
